# Generated by Django 6.0.4 on 2026-04-15 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ObjetConnecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_objet', models.CharField(max_length=100)),
                ('statut', models.CharField(max_length=50)),
                ('batterie', models.IntegerField()),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hopital.chambre')),
            ],
        ),
        migrations.AddField(
            model_name='chambre',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hopital.service'),
        ),
    ]
