# Generated by Django 6.0.4 on 2026-04-27 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('etage', models.IntegerField(blank=True, null=True)),
                ('service', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeEquipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='chambre',
            name='service',
        ),
        migrations.RemoveField(
            model_name='objetconnecte',
            name='chambre',
        ),
        migrations.RemoveField(
            model_name='objetconnecte',
            name='batterie',
        ),
        migrations.RemoveField(
            model_name='objetconnecte',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='objetconnecte',
            name='type_objet',
        ),
        migrations.AddField(
            model_name='objetconnecte',
            name='connectivite',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='objetconnecte',
            name='derniere_interaction',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objetconnecte',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objetconnecte',
            name='etat',
            field=models.CharField(default='inactif', max_length=20),
        ),
        migrations.AddField(
            model_name='objetconnecte',
            name='marque',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='objetconnecte',
            name='niveau_batterie',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objetconnecte',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='DonneeObjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.FloatField()),
                ('unite', models.CharField(max_length=20)),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('objet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hopital.objetconnecte')),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=10, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('type_membre', models.CharField(blank=True, max_length=50, null=True)),
                ('niveau', models.CharField(default='débutant', max_length=20)),
                ('nb_connexions', models.IntegerField(default=0)),
                ('nb_actions', models.IntegerField(default=0)),
                ('statut', models.CharField(default='non validé', max_length=20)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueConnexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('points_gagnes', models.FloatField(default=0.25)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hopital.profil')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(max_length=50)),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('points_gagnes', models.FloatField(default=0.5)),
                ('objet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hopital.objetconnecte')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hopital.profil')),
            ],
        ),
        migrations.CreateModel(
            name='DemandeSuppression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField()),
                ('statut', models.CharField(default='en attente', max_length=20)),
                ('objet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hopital.objetconnecte')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hopital.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hopital.profil')),
            ],
        ),
        migrations.AddField(
            model_name='objetconnecte',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hopital.salle'),
        ),
        migrations.CreateModel(
            name='CompetenceUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.FloatField(default=0)),
                ('niveau', models.CharField(default='débutant', max_length=20)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hopital.profil')),
                ('type_equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hopital.typeequipement')),
            ],
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Chambre',
        ),
    ]
