# Generated by Django 6.0.4 on 2026-04-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0003_service_alter_salle_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='valide',
            field=models.BooleanField(default=False),
        ),
    ]
