# Generated by Django 6.0.4 on 2026-04-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0004_profil_valide'),
    ]

    operations = [
        migrations.AddField(
            model_name='salle',
            name='lits_occupes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salle',
            name='nombre_lits',
            field=models.IntegerField(default=0),
        ),
    ]
